services:
  discovery-service:
    build: ./discovery-service
    container_name: discovery-service
    ports:
      - "8761:8761"
    environment:
      - EUREKA_INSTANCE_HOSTNAME=discovery-service
    networks:
      - bankapp-network

  gateway-service:
    build: ./gateway-service
    container_name: gateway-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_CLOUD_GATEWAY_DISCOVERY_LOCATOR_ENABLED=true
      - EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE=http://discovery-service:8761/eureka/
    depends_on:
      - discovery-service
    networks:
      - bankapp-network


  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:latest
    ports:
      - "8082:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_FRONTEND_URL: http://localhost:8082
      KEYCLOAK_HOSTNAME: keycloak
    volumes:
      - keycloak_data:/var/lib/keycloak/data
    networks:
      - bankapp-network
    command:
      - "start-dev"
      - "-Dkeycloak.profile.feature.scripts=enabled"
      - "-Dkeycloak.profile.feature.upload_scripts=enabled"
  redis:
    image: redis:latest
    container_name: bankapp-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - bankapp-network
    command: redis-server --appendonly yes
volumes:
  keycloak_data:
  redis_data:

networks:
  bankapp-network: