openapi: 3.0.3
info:
  title: Title
  description: Title
  version: 1.0.0
servers:
  - url: 'http://gateway-service:8080'
paths:
  /api/excangeservice:
    post:
      operationId: excangeservice
      summary: Запрос на перевод из одно валюты в другую
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Transfer'
      responses:
        '200':
          description: Изменение данных
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransferValue'
  /api/transferAccountService:
    post:
      summary: перевод между аккаунтами
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Transfer'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransferResponse'
          description: Успешный ответ
  /api/blocker:
    get:
      summary: Блокировка подозрительных операций
      responses:
        '200':
          description: Успешное получение
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BlockerResponse'
  /api/notificationsSet:
    post:
      summary: запрос на уведомление
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Notification'
      responses:
        '200':
          description: успех
components:
  schemas:
    Transfer:
      type: object
      properties:
        from_currency:
          type: string
        to_currency:
          type: string
        value:
          type: number
          format: double
        to_login:
          type: string
        summary:
          type: number
          format: double
    TransferValue:
      type: object
      properties:
        success:
          type: boolean
        summary:
          type: number
          format: double
        cause:
          type: string
    TransferResponse:
      type: object
      properties:
        success:
          type: boolean
        cause:
          type: array
          items:
            type: string
          description: В случаи не верной валидации
    BlockerResponse:
      type: object
      properties:
        success:
          type: boolean
        cause:
          type: string
    Notification:
      type: object
      properties:
        username:
          type: string
        message:
          type: string
        timestamp:
          type: string
          format: datetime

