openapi: 3.0.3
info:
  title: Title
  description: Title
  version: 1.0.0
servers:
  - url: 'http://gateway-service:8080'
paths:
  /api/transfer:
    post:
      summary: Запрос на перевод средств
      security:
        - cookieAuth: []
      parameters:
        - name: SESSION
          in: cookie
          required: true
          schema:
            type: string
          description: "ID сессии пользователя"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Transfer'
      responses:
        '200':
          description: Ответ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransferResponse'
components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: SESSION
  schemas:
    Transfer:
      type: object
      properties:
        from_currency:
          type: string
        to_currency:
          type: string
        value:
          type: number
          format: double
        to_login:
          type: string
        summary:
          type: number
          format: double
    TransferResponse:
      type: object
      properties:
        success:
          type: boolean
        cause:
          type: array
          items:
            type: string
          description: В случаи не верной валидации