openapi: 3.0.3
info:
  title: Title
  description: Title
  version: 1.0.0
servers:
  - url: 'http://gateway-service:8080'
paths:
  /api/excangeservice:
    post:
      operationId: excangeservice
      summary: Запрос на перевод из одно валюты в другую
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Transfer'
      responses:
        '200':
          description: Изменение данных
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransferValue'
components:
  schemas:
    Transfer:
      type: object
      properties:
        from_currency:
          type: string
        to_currency:
          type: string
        value:
          type: number
          format: double
        to_login:
          type: string
    TransferValue:
      type: object
      properties:
        success:
          type: boolean
        summary:
          type: number
          format: double
        cause:
          type: string



