openapi: 3.0.3
info:
  title: Title
  description: Title
  version: 1.0.0
servers:
  - url: 'http://gateway-service:8080'
paths:
  /api/ToAccountServiceTransfer:
    post:
      operationId: transferToAccountService
      summary: Запрос на снятие обналичивание в account-service
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CashTransfer'
      responses:
        '200':
          description: Изменение данных
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountCashResponse'
components:
  schemas:
    AccountCashResponse:
      type: object
      properties:
        success:
          type: boolean
        cause:
          type: array
          items:
            type: string
          description: В случаи не верной валидации
    CashTransfer:
      type: object
      properties:
        currencyTo:
          type: string
        value:
          type: number
          format: double
        action:
          type: string