server:
  port: 8080

spring:
  application:
    name: gateway-service
  data:
    redis:
      host: localhost
      port: 6379
  session:
    timeout: 30m

  servlet:
    session:
      cookie:
        same-site: none
        secure: true # Для HTTPS
        domain: .your-domain.com # Общий домен
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/api/test
          filters:
            - TokenRelay=bankapp
        - id: front-service-signup-get
          uri: lb://front-service
          predicates:
            - Path=/signup
          filters:
            - TokenRelay=bankapp
        - id: front-service-main
          uri: lb://front-service
          predicates:
            - Path=/bankapp
          filters:
            - TokenRelay=bankapp
          metadata:
            allowedHeaders: X-User-Name
            allowAttribute: username
            allowAttributes: username
        - id: front-service-main2
          uri: lb://front-service
          predicates:
            - Path=/
          filters:
            - TokenRelay=bankapp
          metadata:
            allowedHeaders: X-User-Name
            allowAttributes: username
            allowAttribute: username
        - id: account-service-signup-post
          uri: lb://account-service
          predicates:
            - Path=/api/signup
          filters:
            - TokenRelay=bankapp
        - id: account-service-css
          uri: lb://account-service
          predicates:
            - Path=/default-ui.css
          filters:
            - TokenRelay=bankapp
        - id: account-service-mainPage
          uri: lb://account-service
          predicates:
            - Path=/api/getMainPage/**
          filters:
            - TokenRelay=bankapp
          metadata:
            allowedHeaders: X-User-Name
            allowAttribute: username
            allowAttributes: username
        - id: account-service-GetUser
          uri: lb://account-service
          predicates:
            - Path=/api/getUser
          filters:
            - TokenRelay=bankapp
        - id: front-service-editUserAccount
          uri: lb://front-service
          predicates:
            - Path=/editUserAccounts
          filters:
            - TokenRelay=bankapp
          metadata:
            allowedHeaders: X-User-Name
            allowAttributes: username
            allowAttribute: username
        - id: account-service-EditAccount
          uri: lb://account-service
          predicates:
            - Path=/api/editUserAccounts
          filters:
            - TokenRelay=bankapp
          metadata:
            allowedHeaders: X-User-Name
            allowAttributes: username
            allowAttribute: username
        - id: front-service-editUserPassword
          uri: lb://front-service
          predicates:
            - Path=/editPassword
          filters:
            - TokenRelay=bankapp
          metadata:
            allowedHeaders: X-User-Name
            allowAttributes: username
            allowAttribute: username
        - id: account-service-EditPassword
          uri: lb://account-service
          predicates:
            - Path=/api/editPassword
          filters:
            - TokenRelay=bankapp
          metadata:
            allowedHeaders: X-User-Name
            allowAttributes: username
            allowAttribute: username
        - id: ExchangeGenerator-service-getExchange
          uri: lb://ExchangeGenerator-service
          predicates:
            - Path=/api/exchange
          filters:
            - TokenRelay=bankapp
          metadata:
            allowedHeaders: X-User-Name
            allowAttributes: username
            allowAttribute: username
        - id: front-service-exchange
          uri: lb://front-service
          predicates:
            - Path=/exchange
          filters:
            - TokenRelay=bankapp
          metadata:
            allowedHeaders: X-User-Name
            allowAttributes: username
            allowAttribute: username
        - id: front-service-cash
          uri: lb://front-service
          predicates:
            - Path=/cash
          filters:
            - TokenRelay=bankapp
          metadata:
            allowedHeaders: X-User-Name
            allowAttributes: username
            allowAttribute: username
        - id: cash-service-cash
          uri: lb://cash-service
          predicates:
            - Path=/api/cash
          filters:
            - TokenRelay=bankapp
          metadata:
            allowedHeaders: X-User-Name
            allowAttributes: username
            allowAttribute: username
        - id: account-service-EditPassword
          uri: lb://account-service
          predicates:
            - Path=/api/ToAccountServiceTransfer
          filters:
            - TokenRelay=bankapp
          metadata:
            allowedHeaders: X-User-Name
            allowAttributes: username
            allowAttribute: username

      server:
        webflux:
          filter:
            save-session:
              enabled: true

  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/bankapp
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: bankapp
            client-secret: jw49iqTeajZDZH7K3IL3iMDMysz2llXQ
            scope: openid,username
          bankapp:
            provider: keycloak
            authorization-grant-type: client_credentials
            client-id: bankapp
            client-secret: jw49iqTeajZDZH7K3IL3iMDMysz2llXQ
            scope: profile
            client-authentication-method: client_secret_post
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/bankapp
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/bankapp
            user-name-attribute: username

oauth2:
  client:
    registration-id: bankapp
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true


