openapi: 3.0.3
info:
  title: Title
  description: Title
  version: 1.0.0
servers:
  - url: 'http://gateway-service:8080'
paths:
  /api/blocker:
    get:
      summary: Блокировка подозрительных операций
      responses:
        '200':
          description: Успешное получение
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BlockerResponse'
components:
  schemas:
    BlockerResponse:
      type: object
      properties:
        success:
          type: boolean
        cause:
          type: string




