server:
  port: 8083

spring:

  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/bankapp
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: bankapp
            client-secret: jw49iqTeajZDZH7K3IL3iMDMysz2llXQ
            scope: openid,username
          bankapp:
            provider: keycloak
            authorization-grant-type: client_credentials
            client-id: bankapp
            client-secret: jw49iqTeajZDZH7K3IL3iMDMysz2llXQ
            scope: profile
            client-authentication-method: client_secret_post
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/bankapp
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/bankapp
            user-name-attribute: username
  cloud:
    gateway:
      loadbalancer:
        enabled: true
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: front-service
          uri: lb://front-service
          predicates:
            - Path=/signup
          filters:
            - TokenRelay=front-client
          metadata:
            allowedHeaders: X-User-Name
            allowAttribute: username
            allowAttributes: username
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
oauth2:
  client:
    registration-id: bankapp