stage('Build & Unit Tests') {
    parallel {
        stage('Account Service') {
            steps {
                dir('account-service') {
                    sh './gradlew clean test'
                }
            }
        }
        stage('Front Service') {
            steps {
                dir('front-service') {
                    sh './gradlew clean test'
                }
            }
        }
        stage('Cash Service') {
            steps {
                dir('cash-service') {
                    sh './gradlew clean test'
                }
            }
        }
        stage('Transfer Service') {
            steps {
                dir('transfer-service') {
                    sh './gradlew clean test'
                }
            }
        }
    }
}

stage('Build Docker Images') {
    steps {
        script {
            def services = [
                'account-service',
                'blocker-service',
                'cash-service',
                'exchange-service',
                'exchangegenerator-service',
                'front-service',
                'notifications-service',
                'transfer-service'
            ]

            for (def service : services) {
                dir("${service}") {
                    // Сначала собираем JAR файл
                    sh './gradlew build'

                    // Потом собираем Docker образ
                    sh """
                    docker build -t ${DOCKER_REGISTRY}/${service}:${IMAGE_TAG} .
                    """
                }
            }
        }
    }
}