pipeline {
    agent any

    environment {
        DOCKER_REGISTRY = credentials('DOCKER_REGISTRY')
        DB_PASSWORD     = credentials('DB_PASSWORD')
        GITHUB_USERNAME = credentials('GITHUB_USERNAME')
        IMAGE_TAG       = "${env.BUILD_NUMBER}"
        NAMESPACE_DEV   = 'bankapp-dev'
        NAMESPACE_PROD  = 'bankapp-prod'
    }

    stages {
        stage('Fix Permissions') {
                    steps {
                        script {
                            sh '''
                            # Даем права на выполнение gradlew
                            chmod +x gradlew
                            '''
                        }
                    }
                }

                stage('Build & Test All Projects') {
                    steps {
                        sh './gradlew clean test'
                    }
                }

                stage('Build All Services') {
                    steps {
                        sh './gradlew clean build'
                    }
                }

                stage('Build Docker Images') {
                    steps {
                        script {
                            def services = [
                                'account-service', 'blocker-service', 'cash-service',
                                'exchange-service', 'exchangegenerator-service', 'front-service',
                                'notifications-service', 'transfer-service'
                            ]

                            for (def service : services) {
                                dir("${service}") {
                                    sh "docker build -t ${DOCKER_REGISTRY}/${service}:${IMAGE_TAG} ."
                                }
                            }
                        }
                    }
                }

        stage('Push Docker Images') {
            steps {
                withCredentials([string(credentialsId: 'GHCR_TOKEN', variable: 'GHCR_TOKEN')]) {
                    sh """
                    echo \$GHCR_TOKEN | docker login ghcr.io -u ${GITHUB_USERNAME} --password-stdin
                    """

                    script {
                        def services = [
                            'account-service', 'blocker-service', 'cash-service',
                            'exchange-service', 'exchangegenerator-service', 'front-service',
                            'notifications-service', 'transfer-service'
                        ]

                        for (def service : services) {
                            sh "docker push ${DOCKER_REGISTRY}/${service}:${IMAGE_TAG}"
                        }
                    }
                }
            }
        }
        stage('Wait for Kafka') {
            steps {
                sh """
                echo "Waiting for Kafka to be available..."
                kubectl wait --for=condition=ready pod -l app.kubernetes.io/name=kafka \\
                    --namespace kafka-dev --timeout=300s
                """
            }
        }
        stage('Helm Deploy to DEV') {
            steps {
                sh """
                helm upgrade --install bankapp-dev charts/bankapp-umbrella \\
                  --namespace ${NAMESPACE_DEV} --create-namespace \\
                  -f charts/bankapp-umbrella/values-dev.yaml \\
                  --set global.image.repository=${DOCKER_REGISTRY} \\
                  --set global.image.tag=${IMAGE_TAG} \\
                  --set global.image.pullPolicy=Always \\
                  --set infrastructure.keycloak.enabled=true \\
                  --set infrastructure.keycloak.import.enabled=true \\
                  --set infrastructure.ingress.enabled=true \\
                  --debug \\
                  --timeout 5m
                """
            }
        }

        stage('Helm Test') {
            steps {
                script {
                    echo "Waiting for services to be ready..."
                    sh "sleep 300"
                    sh "helm test bankapp-dev --namespace ${NAMESPACE_DEV} --logs || true"
                }
            }
        }

        stage('Manual Approval for PROD') {
            steps {
                input message: 'Deploy to PROD environment?', ok: 'Yes, deploy'
            }
        }

    }

    post {
        success {
            echo "Pipeline completed successfully!"
        }
        failure {
            echo "Pipeline failed!"
        }
    }
}