server:
  port: 8081

spring:

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/api/test
          filters:
            - TokenRelay=account-client

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/bankapp
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/bankapp
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: bankapp
            client-secret: jw49iqTeajZDZH7K3IL3iMDMysz2llXQ
            scope: openid
          bankapp:
            provider: keycloak
            authorization-grant-type: client_credentials
            client-id: bankapp
            client-secret: jw49iqTeajZDZH7K3IL3iMDMysz2llXQ
            scope: profile
            client-authentication-method: client_secret_post



  r2dbc:
    url: r2dbc:postgresql://localhost:5432/bankapp
    username: postgres
    password: 12345
    pool:
      validation-query: SELECT 1
      idle-timeout: 30s
      max-life-time: 5m
      max-size: 10
      initial-size: 5


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
