openapi: 3.0.3
info:
  title: Title
  description: Title
  version: 1.0.0
servers:
  - url: 'http://gateway-service:8080'
paths:
  /api/blocker:
    get:
      summary: Блокировка подозрительных операций
      responses:
        '200':
          description: Успешное получение
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BlockerResponse'
  /api/notificationsSet:
    post:
      summary: запрос на уведомление
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Notification'
      responses:
        '200':
          description: успех
components:
  schemas:
    BlockerResponse:
      type: object
      properties:
        success:
          type: boolean
        cause:
          type: string
    Notification:
      type: object
      properties:
        id:
          type: integer
        username:
          type: string
        message:
          type: string
        timestamp:
          type: string
          format: datetime
    NotificationsGet:
      type: object
      properties:
        Notifications:
          type: array
          items:
            $ref: '#/components/schemas/Notification'